cluster.name: maes-cluster
node.name: maes-node
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

network.host: 0.0.0.0
http.port: 9200

discovery.type: single-node
discovery.seed_hosts: []

xpack.security.enabled: false
xpack.watcher.enabled: false

# Memory settings
bootstrap.memory_lock: true

# Index settings
indices.memory.index_buffer_size: 30%
indices.queries.cache.size: 10%

# Search settings
search.max_buckets: 100000
search.default_search_timeout: 30s

# Thread pool settings
thread_pool:
  write:
    size: 4
    queue_size: 1000
  search:
    size: 4
    queue_size: 1000

# Circuit breaker settings
indices.breaker.total.limit: 70%
indices.breaker.fielddata.limit: 40%
indices.breaker.request.limit: 60%

# Logging
logger.level: INFO 